#!/bin/sh

NAME="single-bare-snis-server"

# Source a litte docker shell library
if [ -f ./docker-shell-library ]
then
	. ./docker-shell-library
else
	if [ -f ./configs/docker-shell-library ]
	then
		. ./configs//docker-shell-library
	fi
fi

exit_if_group_not_docker

usage()
{
	printf "Usage: $0 [ setup | teardown ]\n" 1>&2
	exit 1
}

setup()
{
	echo "Setting up $NAME"
	exit_if_no_such_docker_image snis-server-multiverse-ssgl
	run_or_start_docker_container "$NAME" "snis-server-multiverse-ssgl"
	docker exec -d single-bare-snis-server sh -c \
		'mkdir -p /home/snis/.local/share/space-nerds-in-space ; \
		bin/snis_update_assets --force --destdir /home/snis/.local/share/space-nerds-in-space --srcdir ./share/snis &&  \
		bin/snis_server --allow-remote-networks -L DEFAULT -s default --nolobby -p 45000'
	printf "\n\nConnect your local snis_client instance with 'no lobby' option to 172.17.0.2/45000\n\n"
	return 0;
}

teardown()
{
	echo "Tearing down $NAME"
	stop_and_remove_docker_container "$NAME"
	return $?
}

case "$1" in
	setup)
		setup
		return $?
		;;
	teardown)
		teardown
		return $?
		;;
	*)
		usage
		;;
esac
